dimagi/dimagi-utils

- dimagi/utils/couch/debugdb/__init__.py
- dimagi/utils/django/cache.py
`from django.utils.hashcompat import sha_constructor` no longer exists
> remove unused imports

- dimagi/utils/couch/tastykit.py
- dimagi/utils/decorators/view.py
`HttpRequest.raw_post_data` was renamed to `body` in django 1.4: https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-1-6
> fix raw_post_data

- dimagi/utils/couch/bulk.py
None values cause ChunkedEncodingError: IncompleteRead on cloudant
> filter out empty keys from bulk get_docs

- dimagi/utils/gitinfo.py
Running `./manage.pypreindex_everything ` on a machine with no git binaries yields a confusing `OSError: [Errno 2] No such file or directory` exception message. This PR explicitely shows that git is missing in `OSError.strerror`.
> Show the missing git command in the exception message

- dimagi/utils/couch/bulk.py
make usage of ```requests.post``` consistent with http://docs.python-requests.org/en/v0.10.6/api/#requests.post
> fix get_docs

- dimagi/utils/couch/bulk.py
It seems Cloudant is more strict with boolean query parameters that couchdb
http://manage.dimagi.com/default.asp?163592
> convert params to json

- dimagi/utils/couch/migration.py
@TylerSheffels 
@czue Fyi, this is basically the same migration process you used for the xfoms session migration. Going to be using this to migrate some of the messaging models off couch.
> Add util for handling two-way sync between couch and sql models

- setup.py
they recently removed the redis_cache compatability layer
(todo: upgrade and import django_redis instead?)
This should fix the travis errors. (Wait for build!)
> pin django-redis to <=3.8

- dimagi/ext/jsonobject.py
- dimagi/ext/tests/test_jsonobject.py
cf. [FB 167676][1]. 
This seems to be the right thing to do for now, but longer term I'm guessing we need to migrate the old data, and revert this change.
@snopoke, @dannyroberts, buddy ping @biyeun 
[1]: http://manage.dimagi.com/default.asp?167676
> Allow omitted Z

- dimagi/utils/django/email.py
These are all done within a function, so it should be safe to use
`ugettext`
@sravfeyn
> Change from ugettext_noop to ugettext

- dimagi/test_utils/cache_tests.py
- dimagi/utils/django/cached_object.py
@orangejenny @snopoke just pulled out the call to check all keys. it's a slow call that is [O(N)](http://redis.io/commands/KEYS) with # of keys in the database. hence the reason our slow log looks like this:
All calls to KEYS
> Remove call to get_all_keys

- dimagi/utils/couch/__init__.py
@gcapalbo this seems to be the culprit for our lock timeouts. i played around with the idea of defaulting to `None` but seems like we'd be asking for deadlocks in that case. @dannyroberts i'm thinking these locks timing out led to the document update conflicts when form processing
> Increase timeout

- dimagi/test_utils/__init__.py
- dimagi/utils/django/cached_object.py
- dimagi/utils/tests/__init__.py
- dimagi/utils/tests/cache_tests.py
@snopoke this is a pesky little bugger. should do the trick though. `fetch_meta` returns `{}` on failure. made the tests a bit easier to run too
> Fix is_cached

- dimagi/ext/couchdbkit.py
@NoahCarnahan 
Although this isn't really necessary it helps get rid of spurious 'unused import' warning in pycharm.
> add __all__ to couchdbkit ext

- dimagi/utils/name_to_url.py
- dimagi/utils/tests/name_to_url.py
support https://github.com/dimagi/commcare-hq/pull/8255
drop preceding/trailing hyphens, and add a prefix string if the generated string is all numbers/hyphens
@emord / @kaapstorm
> name_to_url default string & unicode tests

- dimagi/utils/django/cached_object.py
http://manage.dimagi.com/default.asp?183361
> don't crash when missing image metadata on cached lookup

- dimagi/utils/dates.py
- dimagi/utils/tests/dates.py
This works towards allowing DailyFormStatsReport to set a maximum date span, to avoid errors caused by massive DataTable async request headers.
Context: [FB 185304](http://manage.dimagi.com/default.asp?185304)
@snopoke, @czue, cc @millerdev
> Allow DateSpan to set a max number of days

- settings.py
This warning was being spewed a bunch of times when running tests:
```
System check identified some issues:
WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting.
```
@kaapstorm or anyone
> Fix django 1.7 warning

- dimagi/utils/couch/pagination.py
These are each only used in one place, and they already do that anyways.
Also, two bonus cleanup commits (commit-by-commit will be much easier to read, or at least ignore whitespace)
@nickpell
> Require explicitly passing a database

- dimagi/utils/web.py
Spent some time today debugging an issue caused by not having BASE_ADDRESS set, which broke ES in a non-obvious way.
> fail hard if BASE_ADDRESS is missing

- dimagi/utils/couch/cache/cache_core/gen.py
in a previous version about django (haven’t quite pinpointed it,
but there were changes very similar to this noted in release notes
for django 1.6 and 1.7) timeout=0 meant "use the default timeout",
whereas now in 1.7 it means "expire immediately". This meant that
the code the bootstrapped the generational cache generation and
set it to 0 if it didn’t persist in the cache, and thus any new
cache would be perpetually have a generation of the original value
of 0.
should fix http://manage.dimagi.com/default.asp?188411
> fix generational caching

- dimagi/utils/web.py
This'll get rid of the
```
/Users/droberts/.virtualenvs/cchq/lib/python2.7/site-packages/django/contrib/sites/models.py:65: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
class Site(models.Model):
```
that we see at the beginning of every management command
> remove unused Site import

- dimagi/utils/post.py
@czue @TylerSheffels 
essentially we were setting a dictionary with headers:
```
{
content-type: 'text/xml'
Content-type: 'application/json'
}
```
this bug only appeared because `requests` handled it differently than the previous setup.
> Use case insensitive dict

- dimagi/utils/couch/database.py
A useful util for long-running migrations
@benrudolph
> Add retryable version of iter_docs

- dimagi/utils/django/email.py
@czue @millerdev 
This adds the ability to track the open rate of our emails, by sending a request to google analytics upon sending, and adding an empty image that hits GA upon open.
> adding flag to track email opens via ga

- dimagi/utils/couch/database.py
This is useful when you're bulk deleting over a large number of docs.
@calellowitz
> Retry get_docs on failure

- dimagi/utils/decorators/profile.py
@millerdev this adds wraps to `line_profile` so nose can pick up tests that use it
> Wraps for line_profile

- dimagi/utils/dates.py
@sravfeyn @proteusvacuum i think this is what the previous check meant to do. since `datetime` is a subclass of `date` that `if` statement always evaluates to true:
```
In [3]: issubclass(datetime.datetime, datetime.date)
Out[3]: True
```
http://manage.dimagi.com/default.asp?231865#1180917
> Fix datetime check

- dimagi/utils/couch/__init__.py
If the `blocking_timeout` is reached before the lock is acquired then `lock.acquire` return False.
I know we don't use `blocking_timeout` much but seems safe to have this if we ever do
> raise exception if lock not acquired

- dimagi/utils/dates.py
isinstance check for a datetime.datetime object gives a false positive with datetime.date since the former is inherited from the latter so update to check for object type instead
Resolves: http://manage.dimagi.com/default.asp?248226, http://manage.dimagi.com/default.asp?248228
> fix type check for date

- dimagi/utils/post.py
I believe this has been negatively affecting repeater performance, where it is common for people to give us URLs that hang indefinitely.
> Use timeout param
