dimagi/utils/__init__.py
dimagi/utils/make_time.py

only used in PACT; moving there
depends on: https://github.com/dimagi/commcare-hq/pull/6038

remove dimagi.utils.make_time

---

dimagi/utils/couch/bulk.py
dimagi/utils/couch/database.py

allow passing query params to iter_docs

---

dimagi/utils/couch/loosechange.py
dimagi/utils/dates.py
dimagi/utils/decorators/datespan.py

goes along with https://github.com/dimagi/commcare-hq/pull/6235 in spirit but they don't really depend on each other

tidy up references to iso dates

---

dimagi/utils/couch/pagination.py

http://manage.dimagi.com/default.asp?164862
introduced by https://github.com/dimagi/dimagi-utils/pull/253
@kaapstorm buddy ping. @snopoke fyi

properly convert view results to json serializable list

---

dimagi/utils/couch/pagination.py

A fix for a bug that turns out not to be a bug. Wasn't sure whether to drop the change, or push it, and leave the decision to someone else.

Changed mutable default arguments

---

dimagi/utils/couch/bulk.py
dimagi/utils/couch/database.py

co-dependent with https://github.com/dimagi/commcare-hq/pull/6380

change get_docs api to get.... docs

---

dimagi/__init__.py

Seems this isn't necessary any more and is causing issues elsewhere.

remove test imports from init

---

dimagi/ext/couchdbkit.py
dimagi/ext/jsonobject.py
dimagi/ext/models.py
dimagi/ext/tests/__init__.py
dimagi/ext/tests/test_jsonobject.py
dimagi/utils/couch/__init__.py
dimagi/utils/couch/database.py
dimagi/utils/couch/lazy_attachment_doc.py
dimagi/utils/couch/undo.py
dimagi/utils/indicators.py
dimagi/utils/parsing.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/lazy_attachment_doc.py
dimagi/utils/tests/test_json_handler.py
settings.py

(Reopening https://github.com/dimagi/dimagi-utils/pull/265)
Don't merge until https://github.com/dimagi/commcare-hq/pull/6299

Microseconds Everywhere - Dimagi Utils

---

.travis.yml
dimagi/ext/jsonobject.py
dimagi/ext/tests/test_jsonobject.py

http://manage.dimagi.com/default.asp?167670
buddy @sravfeyn 
@dannyroberts FYI

make loose datetime regex more strict

---

dimagi/ext/jsonobject.py
dimagi/ext/tests/test_jsonobject.py

make regex verbose

---

dimagi/ext/jsonobject.py
dimagi/ext/tests/test_jsonobject.py

Reverts dimagi/dimagi-utils#279
I think this is the longer-term solution we're looking for: https://github.com/dimagi/commcare-hq/pull/6576

Revert "Allow omitted Z"

---

dimagi/utils/couch/migration.py

Add option to handle dups in sync to sql

---

dimagi/utils/django/email.py

http://manage.dimagi.com/default.asp?168495
@TylerSheffels @esoergel

notify the user when an email fails to send

---

dimagi/utils/django/email.py

http://manage.dimagi.com/default.asp?170185

fix string formatting

---

dimagi/utils/modules.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/test_modules.py

http://manage.dimagi.com/default.asp?171592
@TylerSheffels

slightly more robust to_function

---

dimagi/utils/name_to_url.py
dimagi/utils/next_available_name.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/name_to_url.py
dimagi/utils/tests/next_available_name.py

Utils to support https://github.com/dimagi/commcare-hq/pull/7106
@sravfeyn / @czue

add name_to_url and next_available_name

---

dimagi/utils/excel.py

See https://github.com/dimagi/commcare-hq/pull/7247/files

print excel file as tuples

---

dimagi/utils/couch/cache/cache_core/__init__.py
dimagi/utils/couch/cache/cache_core/api.py

after last usage has been removed in commcare-hq
merge after: https://github.com/dimagi/commcare-hq/pull/7574

remove cache_core.get_cached_prop, etc.

---

dimagi/utils/couch/migration.py

@gcapalbo 
code buddy @benrudolph

In Sync(Couch|SQL)To(SQL|Couch), sync deletes

---

dimagi/utils/logging.py

fixes http://manage.dimagi.com/default.asp?177091#983061
@gcapalbo 
@esoergel @orangejenny cc @kaapstorm

handle notify exception if request is None

---

dimagi/test_utils/cache_tests.py
dimagi/utils/django/cached_object.py

Reverts dimagi/dimagi-utils#296
this is causing the HQ build to fail

Revert "Remove call to get_all_keys"

---

dimagi/utils/couch/undo.py

update comment and check for None

---

dimagi/utils/couch/sync_docs.py

On the way to better console output while running tests. Logging output is easier to control than prints.

Convert prints to logging calls

---

dimagi/utils/django/email.py

http://manage.dimagi.com/default.asp?178059#edit_0_178059 @esoergel

temporary logging to catch spam

---

dimagi/utils/couch/cache/cache_core/api.py
dimagi/utils/couch/cache/cache_core/gen.py

Update redis package

---

dimagi/utils/couch/cache/cache_core/api.py
dimagi/utils/couch/cache/cache_core/gen.py

Reverts dimagi/dimagi-utils#301

Revert "Update redis package"

---

dimagi/utils/couch/cache/cache_core/__init__.py
dimagi/utils/couch/cache/cache_core/api.py
dimagi/utils/couch/cache/cache_core/gen.py

Reverts dimagi/dimagi-utils#304

Revert "Revert "Update redis package""

---

dimagi/utils/django/cached_object.py

@snopoke this should handle case attachments. don't know what the obsession was with getting all the keys for each method.
cc @orangejenny

Use get over keys

---

dimagi/utils/couch/cache/cache_core/__init__.py
dimagi/utils/couch/cache/cache_core/gen.py

Gets rid of some deprecation warnings for django 1.7

Deprecation

---

dimagi/utils/django/cached_object.py

http://manage.dimagi.com/default.asp?180311
@benrudolph 
cc @NoahCarnahan

check both meta and stream key

---

dimagi/utils/excel.py

should be merged at same time as https://github.com/dimagi/commcare-hq/pull/8072

upgrade openpyxl

---

setup.py

update requirements and bump version

---

dimagi/utils/couch/sync_docs.py

Support for https://github.com/dimagi/commcare-hq/pull/8393
@nickpell / @dannyroberts

Make sync_docs support directories of models

---

dimagi/utils/couch/cache/cache_core/gen.py

http://manage.dimagi.com/default.asp?187591
@orangejenny / up for grabs
easier [without whitespace](https://github.com/dimagi/dimagi-utils/pull/334/files?w=0)

don't fail hard when accessing deleted docs from a cached view

---

dimagi/test_utils/base.py
dimagi/utils/decorators/memoized.py

See discussion here: https://github.com/dimagi/commcare-hq/pull/9329/files#r46170256
@dannyroberts

exclude 'self' from memoize key

---

.travis.yml
dimagi/utils/rate_limit.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/test_rate_limit.py
settings.py

Add simple rate limiting util

---

dimagi/utils/rate_limit.py
dimagi/utils/tests/test_rate_limit.py

Add DomainRateLimiter

---

dimagi/utils/post.py

http://manage.dimagi.com/default.asp?184464
https://confluence.dimagi.com/display/commcarehq/Troubleshooting+Data+Forwarding+Issues
@benrudolph or whoever.

encode unicode data before posting

---

dimagi/utils/couch/sync_docs.py

Merge after https://github.com/dimagi/commcare-hq/pull/9502

delete no longer used code

---

dimagi/utils/post.py

This simplifies the request process here, and should resolve a very transient error: http://manage.dimagi.com/default.asp?189946#1065143

Update calls to simple_post to expect a requests.response

---

dimagi/utils/load_balance.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/test_load_balance.py
dimagi/utils/tests/test_rate_limit.py

@NoahCarnahan @snopoke code review buddies

Add Simple Load Balancing Util

---

dimagi/utils/couch/database.py

Minor updates from https://github.com/dimagi/dimagi-utils/pull/347
@benrudolph @esoergel

PR Feedback

---

dimagi/utils/couch/migration.py

@gcapalbo I'm working on setting up a two-way-sync for locations, but it uses `location_id` instead of `couch_id`

Allow setting of couch_id_name

---

dimagi/utils/couch/pagination.py

Removes dead code from this change: https://github.com/dimagi/commcare-hq/pull/10372

remove unused code

---

dimagi/utils/couch/migration.py

Follow-up from https://github.com/dimagi/dimagi-utils/pull/350
@czue @gcapalbo
The `**{cls._migration_couch_id_name: self._id}` is still pretty ugly, but I don't see a good way around it.

Clarify couch_id_name stuff

---

dimagi/utils/couch/bulk.py
setup.py

companion to https://github.com/dimagi/commcare-hq/pull/10747

use (new) cls.bulk_delete instead of cls.get_db().bulk_delete

---

dimagi/utils/modules.py

catch attribute errors in to_function

---

dimagi/utils/couch/pagination.py

don't use deprecated request.REQUEST

---

dimagi/utils/modules.py

must merge ~~https://github.com/dimagi/commcare-hq/pull/10904~~ https://github.com/dimagi/commcare-hq/pull/10983 first

remove unused try_import

---

dimagi/utils/django/email.py

@czue @millerdev 
Adding the email subject to our email tracking to better allow the product team to understand the data

adding subject line to email tracking

---

dimagi/utils/django/email.py

http://manage.dimagi.com/default.asp?223207
@NoahCarnahan @gcapalbo

encode email subject

---

dimagi/utils/couch/database.py

cf https://github.com/dimagi/commcare-hq/pull/11196

provide callback on bulk delete

---

dimagi/utils/django/email.py

@sravfeyn 
this lets us add any fields to ga email tracking and cleans up the email tracking code a bit

allowing arbitrary extra data to be included in ga email tracking

---

dimagi/utils/decorators/profile.py

@sravfeyn 
as suggested by @czue here: https://github.com/dimagi/commcare-hq/pull/11581#discussion_r63009970

Add resident set size decorator

---

dimagi/utils/couch/database.py

Add function to verify doc types before bulk deleting

---

dimagi/utils/couch/database.py

Add optional wait time to space out bulk delete requests

---

dimagi/utils/couch/database.py

Keep count of all deleted docs

---

dimagi/utils/memory/utils.py

@sravfeyn 
Still looking at memory issues. Here's another tool to help see the size of particular objects.

Add function to show total size of objects

---

dimagi/utils/couch/database.py

Catch a better exception

---

dimagi/utils/django/email.py

http://manage.dimagi.com/default.asp?227529
@benrudolph @emord cc @biyeun

don't fail hard on email analytics tracking

---

dimagi/utils/decorators/profile.py

@emord
Forgot to push this a while ago

garbage collect before printing final usage

---

dimagi/utils/decorators/profile.py

accept string

---

dimagi/requirements.txt

remove selenium dep

---

dimagi/utils/dates.py

do correct datetime date comparisons

---

dimagi/ext/tests/__init__.py
dimagi/utils/tests/__init__.py
dimagi/utils/tests/test_modules.py

Remove test imports for django test runner

---

.travis.yml
dimagi/utils/management/commands/flush_caches.py

replace LabelCommand with BaseCommand

---

dimagi/utils/indicators.py
setup.py

default to None to allow differenciating between False and not set

---

dimagi/utils/multithreading.py

see https://github.com/dimagi/commcare-hq/pull/13877

remove reference to couchlog

---

dimagi/utils/dates.py

add DateSpan.max()

---

dimagi/utils/decorators/memoized.py

remove backwards compatible code for python 2.6

---

dimagi/ext/jsonobject.py

that just subclasses JsonObject with _allow_dynamic_properties = False
@esoergel

add helpful StrictJsonObject object

---

dimagi/utils/dates.py

was super confused trying to print a datespan for an entire year and having it show as "january 2015"
@NoahCarnahan / anyone

fix logic for displaying a datespan like a month

---

dimagi/utils/decorators/profile.py

@czue adds wraps to profile decorator so that it works with tests
cc: @kaapstorm

Add wraps to profile decorator

---

dimagi/utils/logging.py

cross: https://github.com/dimagi/commcare-hq/pull/15114

allow supplying exec info + signal logging util

---

dimagi/utils/couch/undo.py
dimagi/utils/tests/test_undo.py

small utilities to support https://github.com/dimagi/commcare-hq/pull/15191/

undo delete

---

dimagi/utils/management/commands/flush_caches.py
dimagi/utils/management/commands/prime_views.py

remove unused *args from handle()

---

dimagi/utils/couch/bulk.py

short circuit request

---

dimagi/utils/couch/bulk.py

generate uuid's in python

---

dimagi/utils/couch/database.py

This should be fine to merge now since this setting exists already

don't use old setting

---

dimagi/utils/post.py

Needed for some hq repeater work I'm doing.
buddy @gcapalbo 
FYI @proteusvacuum

Add auth kwarg to simple_post

---

dimagi/utils/couch/database.py

@snopoke any reason why this wasn't create before? your couch 2 pr points to it and it looks safe to merge

alternate 'bigcouch' setting

---

dimagi/utils/couch/sync_docs.py

https://github.com/dimagi/commcare-hq/pull/16444
@orangejenny

force reindex

---

dimagi/utils/web.py

Don't always cast "true" and "false" to python bools
